version: '3.0'  

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    container_name: 'frontend'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:80'
    environment:
      - API_URL=http://localhost:5000